export type ResourceStatus = "verified" | "tad-built" | "review" | "reference";

export type Resource = {
  name: string;
  category: string;
  status: ResourceStatus;
  summary: string;
  url: string;
  exampleUrl?: string;
  note?: string;
  tags: string[];
};

export type TimelineSource = {
  label: string;
  url: string;
};

export type TimelineEvent = {
  id: string;
  year: string;
  date: string;
  era: "Foundations" | "Breakthroughs" | "Generative AI" | "Governance & culture";
  title: string;
  summary: string;
  significance: string;
  sources: TimelineSource[];
};

export const statusLabels: Record<ResourceStatus, string> = {
  verified: "Verified",
  "tad-built": "TAD-built",
  review: "Emerging",
  reference: "Reference",
};

export const resources: Resource[] = [
  {
    name: "Adobe Firefly",
    category: "Illustration",
    status: "verified",
    summary: "A mature creative-AI workspace for image, video, audio, and vector generation inside Adobe workflows.",
    url: "https://www.adobe.com/products/firefly.html",
    note: "Strong production integration and Content Credentials support. Verify the current plan and model-specific commercial terms.",
    tags: ["image generation", "creative suite", "Content Credentials", "Adobe"],
  },
  {
    name: "Nano Banana / Gemini Images",
    category: "Illustration",
    status: "verified",
    summary: "Fast image generation and editing with strong conversational control over characters, layout, and revisions.",
    url: "https://gemini.google.com/",
    exampleUrl: "https://youtu.be/lfE-csUyPF4",
    tags: ["image editing", "characters", "composition", "Gemini"],
  },
  {
    name: "Midjourney",
    category: "Illustration",
    status: "verified",
    summary: "A high-quality image system for concept art, visual development, reference-driven variation, and style exploration.",
    url: "https://www.midjourney.com/",
    note: "Use references and style imitation carefully; document authorship, sources, and substantial human revision.",
    tags: ["image generation", "concept art", "visual development", "style"],
  },
  {
    name: "Ideogram",
    category: "Illustration",
    status: "verified",
    summary: "A design-aware image model with especially useful typography, layout, editing, and high-resolution output.",
    url: "https://ideogram.ai/",
    tags: ["typography", "layout", "image generation", "editing"],
  },
  {
    name: "FLUX / Black Forest Labs",
    category: "Illustration",
    status: "verified",
    summary: "A professional image-model family with strong generation and editing capabilities plus an important open-model ecosystem.",
    url: "https://bfl.ai/models",
    note: "A likely foundation for many future creative tools; model licenses differ, so check the exact checkpoint before use.",
    tags: ["image models", "editing", "open ecosystem", "API"],
  },
  {
    name: "ComfyUI",
    category: "Illustration",
    status: "verified",
    summary: "A modular, node-based creation engine for controlled image, video, 3D, and audio pipelines.",
    url: "https://github.com/Comfy-Org/ComfyUI",
    note: "Excellent for advanced, reproducible workflows; the learning curve and third-party node security require care.",
    tags: ["node workflow", "local AI", "automation", "open source"],
  },
  {
    name: "LoRA Training Workflow",
    category: "Illustration",
    status: "tad-built",
    summary: "A TAD-created workflow for training a distinctive character or visual style for reuse across compatible tools.",
    url: "https://ior.ad/b5nn?iframeHash=trysteps-1",
    tags: ["training", "style consistency", "character consistency"],
  },
  {
    name: "Krita Live Drawing Workflow",
    category: "Illustration",
    status: "tad-built",
    summary: "A locally controlled workflow that turns live drawing changes into AI-rendered iterations without sharing the original artwork.",
    url: "https://www.iorad.com/player/2628799/How-to-use-Krita-live-generative-AI-tool-on-AI-computer-",
    tags: ["Krita", "local AI", "live drawing", "tutorial"],
  },
  {
    name: "Recraft",
    category: "Graphic Design",
    status: "verified",
    summary: "A design-focused platform for editable graphics, vector generation, mockups, icon systems, and brand assets.",
    url: "https://www.recraft.ai/",
    tags: ["vector", "mockups", "icons", "brand assets"],
  },
  {
    name: "Figma AI & Make",
    category: "Graphic Design",
    status: "verified",
    summary: "AI-assisted design, prototyping, and code generation embedded in a collaborative professional design platform.",
    url: "https://www.figma.com/ai/",
    exampleUrl: "https://www.figma.com/make/",
    note: "A strong candidate for an industry-standard design-to-code workflow because it connects editable design systems, prototypes, and team review.",
    tags: ["UI design", "prototyping", "design systems", "code generation"],
  },
  {
    name: "Canva AI / Magic Studio",
    category: "Graphic Design",
    status: "verified",
    summary: "An accessible, integrated suite for layouts, branded content, presentations, images, video, and collaborative editing.",
    url: "https://www.canva.com/canva-ai/",
    note: "High workflow maturity and broad adoption; users remain responsible for rights to uploaded and generated material.",
    tags: ["layout", "brand kit", "presentations", "creative suite"],
  },
  {
    name: "Topaz Labs",
    category: "Graphic Design",
    status: "verified",
    summary: "Professional AI-assisted image and video restoration for denoising, sharpening, stabilization, and upscaling.",
    url: "https://www.topazlabs.com/",
    tags: ["restoration", "upscaling", "image quality", "video enhancement"],
  },
  {
    name: "Napkin AI",
    category: "Graphic Design",
    status: "review",
    summary: "Turns structured text into editable diagrams and visual explainers for presentations and process documentation.",
    url: "https://www.napkin.ai/",
    note: "Promising for rapid communication graphics; verify factual accuracy and refine hierarchy, spacing, and accessibility by hand.",
    tags: ["diagrams", "explainer", "presentation", "visualization"],
  },
  {
    name: "Runway",
    category: "Animation & Video",
    status: "verified",
    summary: "A mature creative-video platform for generation, editing, performance capture, motion control, and production workflows.",
    url: "https://runwayml.com/",
    exampleUrl: "https://help.runwayml.com/hc/en-us/articles/42311337895827-Performance-Capture-with-Act-Two",
    tags: ["video generation", "performance capture", "editing", "motion control"],
  },
  {
    name: "Google Flow / Veo",
    category: "Animation & Video",
    status: "verified",
    summary: "A filmmaker-oriented workspace for generating shots, extending scenes, and assembling controlled video sequences with Veo.",
    url: "https://labs.google/fx/tools/flow",
    tags: ["video generation", "filmmaking", "scene building", "Veo"],
  },
  {
    name: "Luma Dream Machine",
    category: "Animation & Video",
    status: "verified",
    summary: "A production-capable video workspace for text, image, and footage generation, transformation, continuity, and editing.",
    url: "https://lumalabs.ai/create",
    tags: ["video generation", "video editing", "continuity", "creative direction"],
  },
  {
    name: "Kling AI",
    category: "Animation & Video",
    status: "verified",
    summary: "A high-quality video system with native audio, multi-shot control, element consistency, and reference-driven generation.",
    url: "https://app.klingai.com/global/",
    note: "Strong current capability; review privacy, access, and commercial-use terms for each project.",
    tags: ["video generation", "native audio", "multi-shot", "consistency"],
  },
  {
    name: "HeyGen",
    category: "Animation & Video",
    status: "verified",
    summary: "A mature avatar, dubbing, lip-sync, and video-localization platform with broad language support.",
    url: "https://www.heygen.com/",
    note: "Obtain explicit consent for a person’s likeness and voice, and clearly disclose synthetic presenters where appropriate.",
    tags: ["avatars", "dubbing", "translation", "lip sync"],
  },
  {
    name: "Autodesk Flow Studio",
    category: "Animation & Video",
    status: "verified",
    summary: "AI-assisted visual-effects production for motion capture, camera tracking, CG character placement, rigging, and editable export.",
    url: "https://www.autodesk.com/products/flow-studio/overview",
    note: "Its editable handoff to Maya, Blender, Unreal, and 3ds Max makes it a strong candidate for standard production pipelines.",
    tags: ["motion capture", "VFX", "camera tracking", "3D export"],
  },
  {
    name: "Mixamo",
    category: "Animation & Video",
    status: "verified",
    summary: "A dependable Adobe service for automatic character rigging and applying a large library of reusable motion clips.",
    url: "https://www.mixamo.com/",
    tags: ["rigging", "character animation", "motion library", "Adobe"],
  },
  {
    name: "LTX Studio",
    category: "Animation & Video",
    status: "review",
    summary: "An integrated script-to-screen workspace for storyboards, scene generation, timelines, pitch materials, and team production.",
    url: "https://ltx.studio/",
    note: "Promising as an end-to-end filmmaking system; continue testing consistency, editorial control, and final-output quality.",
    tags: ["filmmaking", "storyboarding", "timeline", "production planning"],
  },
  {
    name: "Hera",
    category: "Motion Graphics",
    status: "review",
    summary: "Prompt-driven motion graphics for explainer videos, brand systems, and quick animated compositions.",
    url: "https://hera.video/",
    note: "A credible emerging specialist; compare its editability and motion quality with authored After Effects workflows.",
    tags: ["motion graphics", "brand kit", "explainer video", "animation"],
  },
  {
    name: "Meshy",
    category: "3D & CAD",
    status: "verified",
    summary: "A production-oriented text- and image-to-3D platform with textured assets, animation tools, and broad export support.",
    url: "https://www.meshy.ai/",
    note: "Useful for rapid base assets; topology, scale, materials, and fabrication readiness still require expert inspection.",
    tags: ["text to 3D", "image to 3D", "texturing", "export"],
  },
  {
    name: "Tripo AI",
    category: "3D & CAD",
    status: "review",
    summary: "Fast text- and image-to-3D generation with a plausible role in concept modeling and asset-blockout workflows.",
    url: "https://www.tripo3d.ai/",
    note: "Promising, but generated topology and production readiness should be tested on real downstream tasks.",
    tags: ["text to 3D", "image to 3D", "model generation", "blockout"],
  },
  {
    name: "Zoo",
    category: "3D & CAD",
    status: "review",
    summary: "A text-to-CAD system exploring editable, parametric geometry for engineering and fabrication workflows.",
    url: "https://zoo.dev/",
    note: "High industry potential if generated geometry remains constrained, editable, and fabrication-ready.",
    tags: ["text to CAD", "parametric modeling", "fabrication", "engineering"],
  },
  {
    name: "ChatGPT",
    category: "Apps & Games",
    status: "verified",
    summary: "A general-purpose AI workspace for research, coding, prototyping, critique, file analysis, and multimodal creative work.",
    url: "https://chatgpt.com/",
    note: "Verification applies to defined, reviewable workflows—not to every answer, generated claim, or use case.",
    tags: ["coding", "research", "prototyping", "multimodal"],
  },
  {
    name: "Google AI Studio",
    category: "Apps & Games",
    status: "verified",
    summary: "A capable environment for testing Gemini models and building code-driven apps, games, and multimodal prototypes.",
    url: "https://aistudio.google.com/",
    tags: ["coding", "prototyping", "apps", "Gemini"],
  },
  {
    name: "GitHub Copilot",
    category: "Apps & Games",
    status: "verified",
    summary: "A mature coding-agent ecosystem across editors, GitHub, and the command line for writing, reviewing, testing, and maintaining software.",
    url: "https://github.com/features/copilot",
    tags: ["coding agent", "GitHub", "IDE", "code review"],
  },
  {
    name: "Claude Code",
    category: "Apps & Games",
    status: "verified",
    summary: "A strong agentic coding tool for understanding codebases, editing files, running commands, and completing multi-step development work.",
    url: "https://www.anthropic.com/claude-code",
    tags: ["coding agent", "terminal", "codebase", "automation"],
  },
  {
    name: "Cursor",
    category: "Apps & Games",
    status: "verified",
    summary: "An AI-native code editor with codebase-aware agents for planning, writing, reviewing, testing, and maintaining software.",
    url: "https://cursor.com/",
    note: "Generated changes still require tests, type checks, security review, and human approval.",
    tags: ["coding agent", "IDE", "code review", "automation"],
  },
  {
    name: "Vercel v0",
    category: "Apps & Games",
    status: "verified",
    summary: "A polished prompt-to-full-stack builder for generating, iterating, connecting, and deploying modern web applications.",
    url: "https://v0.dev/",
    tags: ["app builder", "web development", "React", "deployment"],
  },
  {
    name: "Gemini Notebook",
    category: "Research & Learning",
    status: "verified",
    summary: "A source-grounded research and learning workspace for analyzing course materials, documents, notes, audio, and web sources with citations.",
    url: "https://notebooklm.google/",
    note: "Formerly NotebookLM. Strong for source-bound synthesis; verify important conclusions against the cited originals.",
    tags: ["research", "citations", "study guides", "source analysis"],
  },
  {
    name: "Hugging Face Hub",
    category: "Research & Learning",
    status: "verified",
    summary: "A foundational open platform for discovering, documenting, testing, and sharing AI models, datasets, and demonstrations.",
    url: "https://huggingface.co/",
    note: "Quality and licenses vary by repository; inspect model cards, provenance, safety notes, and usage terms before adoption.",
    tags: ["open models", "datasets", "model cards", "research"],
  },
  {
    name: "ElevenLabs",
    category: "Audio",
    status: "verified",
    summary: "A professional voice platform for narration, speech synthesis, dubbing, voice design, localization, and audio production.",
    url: "https://elevenlabs.io/",
    note: "Require consent for cloned voices and disclose synthetic speech when context calls for it.",
    tags: ["synthetic voice", "narration", "dubbing", "localization"],
  },
  {
    name: "Descript",
    category: "Audio",
    status: "verified",
    summary: "A mature text-based audio and video editor for transcription, cleanup, revision, captions, and collaborative production.",
    url: "https://www.descript.com/",
    tags: ["transcription", "audio editing", "video editing", "captions"],
  },
  {
    name: "Adobe Podcast",
    category: "Audio",
    status: "verified",
    summary: "A focused browser workflow for enhancing spoken audio, recording remotely, transcribing, and editing speech.",
    url: "https://podcast.adobe.com/",
    tags: ["speech cleanup", "podcast", "transcription", "Adobe"],
  },
  {
    name: "Suno",
    category: "Audio",
    status: "verified",
    summary: "A capable music-generation platform with song development, extensions, stems, and a generative audio workstation.",
    url: "https://suno.com/",
    note: "Quality is strong, but commercial rights, training-data concerns, and plan-specific ownership require project-level review.",
    tags: ["music generation", "songwriting", "stems", "audio workstation"],
  },
  {
    name: "LALAL.AI",
    category: "Audio",
    status: "verified",
    summary: "A reliable specialist for stem separation, voice cleanup, noise reduction, and isolating parts of a recorded mix.",
    url: "https://www.lalal.ai/",
    tags: ["stem separation", "audio cleanup", "noise removal", "voice"],
  },
  {
    name: "C2PA Content Credentials",
    category: "Responsible Practice",
    status: "verified",
    summary: "The open technical standard for attaching tamper-evident provenance and edit-history signals to digital media.",
    url: "https://c2pa.org/",
    exampleUrl: "https://spec.c2pa.org/specifications/specifications/2.4/explainer/Explainer.html",
    note: "A leading candidate for an industry-wide provenance standard. Credentials provide history and trust signals, not a verdict that content is true.",
    tags: ["provenance", "authenticity", "open standard", "Content Credentials"],
  },
  {
    name: "Glaze & Nightshade",
    category: "Responsible Practice",
    status: "verified",
    summary: "University of Chicago tools that help artists resist unauthorized style mimicry and unconsented model training.",
    url: "https://glaze.cs.uchicago.edu/",
    note: "Verified for their stated protective purpose, not as a guarantee against every present or future attack.",
    tags: ["artist protection", "consent", "style mimicry", "research"],
  },
];

export const workflows = [
  {
    number: "01",
    title: "Consistent illustration",
    category: "Illustration",
    steps: ["Define a character or style", "Build a controlled node workflow", "Refine by hand", "Record sources and edits"],
    tools: ["LoRA Training", "ComfyUI", "Krita Live Drawing"],
  },
  {
    number: "02",
    title: "Character to motion",
    category: "Animation",
    steps: ["Prepare the character", "Rig or transfer performance", "Correct motion", "Composite and credit"],
    tools: ["Runway", "Autodesk Flow Studio", "Mixamo"],
  },
  {
    number: "03",
    title: "Prompt to physical form",
    category: "3D & CAD",
    steps: ["Generate a base asset", "Repair topology or constraints", "Check scale and tolerances", "Prototype or fabricate"],
    tools: ["Meshy", "Tripo AI", "Zoo"],
  },
  {
    number: "04",
    title: "Song idea to editable mix",
    category: "Audio",
    steps: ["Capture the musical idea", "Generate or extend", "Separate and clean stems", "Edit, mix, and document rights"],
    tools: ["Suno", "LALAL.AI", "Adobe Podcast"],
  },
  {
    number: "05",
    title: "Idea to working prototype",
    category: "Apps & Games",
    steps: ["Define the smallest test", "Generate a first build", "Run tests and debug", "Review access, security, and ownership"],
    tools: ["Figma AI & Make", "Vercel v0", "GitHub Copilot"],
  },
  {
    number: "06",
    title: "Source-grounded research",
    category: "Research",
    steps: ["Collect authoritative sources", "Ask bounded questions", "Follow every citation", "Separate evidence from inference"],
    tools: ["Gemini Notebook", "Hugging Face model cards", "Primary sources"],
  },
  {
    number: "07",
    title: "Critical tool evaluation",
    category: "Responsible use",
    steps: ["Test a real task", "Read terms and limitations", "Check consent and provenance", "Document failures and uncertainty"],
    tools: ["C2PA Content Credentials", "Glaze & Nightshade", "Verification rubric"],
  },
];

export const projectIdeas = [
  { title: "Bobble head", domain: "Illustration + 3D", format: "Physical prototype" },
  { title: "Animated comic book", domain: "Illustration + Motion", format: "Narrative experiment" },
  { title: "Narrated video", domain: "Animation + Audio", format: "Short video" },
  { title: "Motion graphics study", domain: "Motion Graphics", format: "Screen-based sequence" },
  { title: "AI history timeline", domain: "Art Education", format: "Interactive learning object" },
  { title: "Exhibit media kit", domain: "Exhibit Design", format: "Video + spatial assets" },
  { title: "HTML web app", domain: "App Development", format: "Functional prototype" },
  { title: "Portfolio website", domain: "Website Design", format: "Published site" },
  { title: "E-book", domain: "Publishing", format: "Interactive document" },
  { title: "Live video to AI", domain: "Experimental Media", format: "Performance test" },
  { title: "AI trainer journey", domain: "Project Management", format: "Process documentation" },
  { title: "Resistor / settler zine", domain: "Critical Design", format: "10-page zine or 3–5 minute video" },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "logical-neuron-1943",
    year: "1943",
    date: "December 1943",
    era: "Foundations",
    title: "A mathematical model of the neuron",
    summary: "Warren McCulloch and Walter Pitts described simplified artificial neurons using logic, linking computation and theories of the brain.",
    significance: "The paper supplied an early conceptual foundation for neural networks—even though its model of biology was deliberately simplified.",
    sources: [
      { label: "Original paper", url: "https://doi.org/10.1007/BF02478259" },
    ],
  },
  {
    id: "turing-test-1950",
    year: "1950",
    date: "October 1950",
    era: "Foundations",
    title: "Turing reframes machine intelligence",
    summary: "Alan Turing's “Computing Machinery and Intelligence” proposed the imitation game as a practical way to discuss whether machines can think.",
    significance: "The paper shifted attention from defining thought to examining observable performance, an argument that still shapes AI evaluation.",
    sources: [
      { label: "Original paper", url: "https://academic.oup.com/mind/article/LIX/236/433/986238" },
    ],
  },
  {
    id: "dartmouth-1956",
    year: "1956",
    date: "Summer 1956",
    era: "Foundations",
    title: "Artificial intelligence becomes a field",
    summary: "The Dartmouth Summer Research Project brought researchers together around a proposal that named and framed “artificial intelligence.”",
    significance: "The workshop helped establish AI as a distinct research program with questions about language, learning, abstraction, and creativity.",
    sources: [
      { label: "Dartmouth history", url: "https://home.dartmouth.edu/about/artificial-intelligence-ai-coined-dartmouth" },
      { label: "Original proposal", url: "https://www-formal.stanford.edu/jmc/history/dartmouth/dartmouth.html" },
    ],
  },
  {
    id: "deep-blue-1997",
    year: "1997",
    date: "May 11, 1997",
    era: "Breakthroughs",
    title: "Deep Blue defeats the world chess champion",
    summary: "IBM's Deep Blue defeated Garry Kasparov in a six-game rematch, demonstrating the power of specialized computation and large-scale search.",
    significance: "The victory became a public symbol of machine capability while also showing how narrow expertise differs from general intelligence.",
    sources: [
      { label: "IBM history", url: "https://www.ibm.com/history/deep-blue" },
    ],
  },
  {
    id: "alexnet-2012",
    year: "2012",
    date: "December 2012",
    era: "Breakthroughs",
    title: "AlexNet changes computer vision",
    summary: "A deep convolutional neural network dramatically improved performance in the ImageNet competition using GPUs, large datasets, and learned features.",
    significance: "AlexNet accelerated the modern deep-learning wave and changed how visual recognition systems were designed and trained.",
    sources: [
      { label: "NeurIPS paper", url: "https://proceedings.neurips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks" },
    ],
  },
  {
    id: "transformer-2017",
    year: "2017",
    date: "June 12, 2017",
    era: "Breakthroughs",
    title: "The transformer architecture arrives",
    summary: "“Attention Is All You Need” introduced a sequence architecture built around attention rather than recurrent or convolutional layers.",
    significance: "Transformers became the core architecture behind many modern language, image, audio, and multimodal systems.",
    sources: [
      { label: "Research paper", url: "https://arxiv.org/abs/1706.03762" },
    ],
  },
  {
    id: "chatgpt-2022",
    year: "2022",
    date: "November 30, 2022",
    era: "Generative AI",
    title: "ChatGPT brings conversational AI to a mass audience",
    summary: "OpenAI released ChatGPT as a public research preview, making a dialogue-based large language model broadly accessible.",
    significance: "The release rapidly changed public expectations, classroom policy, creative workflows, and investment across the technology sector.",
    sources: [
      { label: "OpenAI announcement", url: "https://openai.com/index/chatgpt/" },
    ],
  },
  {
    id: "eu-ai-act-2024",
    year: "2024",
    date: "August 1, 2024",
    era: "Governance & culture",
    title: "The European Union AI Act enters into force",
    summary: "The EU adopted a comprehensive, risk-based legal framework governing the development and use of artificial intelligence.",
    significance: "Its phased requirements made AI governance a design, documentation, transparency, and compliance concern—not only a technical one.",
    sources: [
      { label: "Official regulation", url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng" },
      { label: "EU implementation timeline", url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" },
    ],
  },
  {
    id: "bartz-ruling-2025",
    year: "2025",
    date: "June 23, 2025",
    era: "Governance & culture",
    title: "Bartz v. Anthropic separates training from piracy",
    summary: "A federal district court held that Anthropic's LLM training was fair use and that replacing purchased print books with internal digital copies was fair use, but rejected fair use for its permanent library of pirated books.",
    significance: "The decision is influential but narrow: it is one district-court ruling, it distinguished multiple kinds of copying, and it did not create a blanket exemption for AI companies.",
    sources: [
      { label: "Court order", url: "https://copyrightalliance.org/wp-content/uploads/2025/06/Bartz-v.-Anthropic-Order.pdf" },
      { label: "AP explanation", url: "https://apnews.com/article/1e5cece51c2e4bd0bb21d94de2abb035" },
    ],
  },
  {
    id: "anthropic-settlement-2026",
    year: "2026",
    date: "July 20, 2026",
    era: "Governance & culture",
    title: "$1.5 billion Anthropic book settlement approved",
    summary: "A federal judge granted final approval to the class settlement covering more than 482,000 books obtained from pirate libraries, with roughly $3,000 allocated per covered work before distribution adjustments.",
    significance: "The settlement compensates rightsholders for pirated acquisition; it does not reverse the earlier fair-use ruling for model training or establish that all training on copyrighted material is lawful.",
    sources: [
      { label: "Final approval order", url: "https://publishers.org/wp-content/uploads/2026/07/Order-Granting-Final-Approval-of-Settlement171.pdf" },
      { label: "AP report", url: "https://apnews.com/article/ai-anthropic-copyright-settlement-claude-books-bartz-74b140444023898aeba8579b6e9f0d63" },
    ],
  },
  {
    id: "amazon-book-scanning-2026",
    year: "2026",
    date: "August 17, 2026",
    era: "Governance & culture",
    title: "Investigation traces rare books to Amazon scanning facility",
    summary: "404 Media tracked a shipment to an Amazon facility where employees said printed books were cut apart, scanned for AI training data, and destroyed in the process.",
    significance: "The investigation supports concern that destructive scanning extends beyond Anthropic, while the buyers behind other unusual bulk book orders remain uncertain.",
    sources: [
      { label: "404 Media investigation", url: "https://www.404media.co/we-tracked-a-shipment-of-rare-books-it-ended-at-an-amazon-ai-training-facility/" },
      { label: "TechCrunch summary", url: "https://techcrunch.com/2026/08/17/amazon-once-an-online-bookseller-is-destroying-rare-books-to-train-ai-models/" },
    ],
  },
];

export const learningResources = [
  {
    title: "Original TAD History of AI timeline",
    type: "Tiki-Toki archive",
    summary: "The original external timeline remains available while the native timeline in this resource hub becomes the maintained version.",
    url: "https://www.tiki-toki.com/timeline/entry/2196919/History-Of-AI",
  },
  {
    title: "AI for Art & Design",
    type: "TADD 2310 Prezi",
    summary: "The course presentation that frames AI in relation to creative practice, critique, and design workflows.",
    url: "https://prezi.com/view/hA7y76syYIEjPvflo1nh/?referral_token=PsDn3ylnB3FN",
  },
  {
    title: "AI Course Outline",
    type: "TAD course document",
    summary: "Working outline for the AI for Art & Design course. Institutional sign-in may be required.",
    url: "https://mnscu.sharepoint.com/:w:/r/teams/BSU-DigitalCorps540-Team/Shared%20Documents/AI%20Research%20and%20Development%20Corps/AI%20Class%20Resources/Course%20Outline.docx",
  },
  {
    title: "TAD AI Links",
    type: "Link collection",
    summary: "The existing TAD AI link collection for resources that have not yet been fully structured here.",
    url: "https://linktr.ee/TAD_AI",
  },
  {
    title: "C2PA Content Credentials explainer",
    type: "Open provenance standard",
    summary: "An authoritative introduction to verifiable media provenance, edit history, trust signals, and their limits.",
    url: "https://spec.c2pa.org/specifications/specifications/2.4/explainer/Explainer.html",
  },
  {
    title: "The Glaze Project",
    type: "Artist protection research",
    summary: "Research, software, and practical guidance on resisting style mimicry and training without consent.",
    url: "https://glaze.cs.uchicago.edu/",
  },
  {
    title: "Algorithmic due process and State v. Loomis",
    type: "Law and accountability",
    summary: "A legal resource for examining attribution, accountability, and due process in algorithmic systems.",
    url: "https://jolt.law.harvard.edu/digest/algorithmic-due-process-mistaken-accountability-and-attribution-in-state-v-loomis-1",
  },
  {
    title: "The dangers of AI-social media integration",
    type: "Critical reading",
    summary: "A critical resource on disinformation, engagement systems, and the social consequences of generative AI.",
    url: "https://www.theatlantic.com/technology/archive/2023/05/generative-ai-social-media-integration-dangers-disinformation-addiction/673940/",
  },
  {
    title: "The limits of AI-generated Miyazaki",
    type: "Art and authorship",
    summary: "A cultural critique for discussing style imitation, authorship, and what generation misses about artistic practice.",
    url: "https://www.newyorker.com/culture/infinite-scroll/the-limits-of-ai-generated-miyazaki",
  },
  {
    title: "Andy Warhol and art judging art",
    type: "Audio / legal context",
    summary: "A podcast resource connecting appropriation, transformation, and legal judgment in art.",
    url: "https://www.wnycstudios.org/podcasts/radiolabmoreperfect/episodes/andy-warhol-and-art-judging-art",
  },
  {
    title: "Anthropic book piracy settlement",
    type: "Copyright and AI training",
    summary: "AP's overview of the $1.5 billion settlement, paired in the native timeline with the underlying fair-use and final-approval orders.",
    url: "https://apnews.com/article/ai-anthropic-copyright-settlement-claude-books-bartz-74b140444023898aeba8579b6e9f0d63",
  },
  {
    title: "Amazon destructive book-scanning investigation",
    type: "Training data and cultural preservation",
    summary: "404 Media's investigation tracing a rare-book shipment to an Amazon facility that cuts, scans, and destroys books for AI training data.",
    url: "https://www.404media.co/we-tracked-a-shipment-of-rare-books-it-ended-at-an-amazon-ai-training-facility/",
  },
];
